### ISSUE TITLE
scanData Problem

### ISSUE THREAD

**Issue by hosseinadib-hub** [faraday/wikiprep-esa#1]
thank you for your complete Source code
Sorry if it is wrong place for this questions.

i have a problem,
When i run scanData.py, it ask me Disambig file , Where can i Find Disambig file ?
and is your Wikipedia Snapshop  "Gabrilovich" ?
And how much Ram require for run this Code with this snapshot ?

Thanks

**Comment by faraday** [comment]
Zemanta version of Wikiprep produces a file listing disambiguation articles ending with .disambig (such as "enwiki-20090618.disambig"). This file contains lines in this format:

> "Disambig page id" **tab** "Target page id (or 'undef')" **tab** "Target anchor"

Example:

> 780     47427   Atlas (moon)

Actually, the only thing scanData uses from this file is **Disambig page id** and it picks that after splitting the line at  tab (\t) characters.

What do you mean by 'is your Wikipedia Snapshot "Gabrilovich" '? Do you mean format string ? I used "Gabrilovich" as format string when I was working with the snapshot from Gabrilovich et al, available at: 
http://www.cs.technion.ac.il/~gabr/resources/code/wikiprep/

Direct link: http://www.cs.technion.ac.il/~gabr/resources/code/wikiprep/wikipedia-051105-preprocessed.tar.bz2

About RAM usage:
Python scripts should work on a decent machine with every dump, since they don't require high amounts of RAM and do sequential processing. However, you will still need LOTS of RAM (16 GB etc.) and LOTS of processing power to run Wikiprep first (as explained by Zemanta team: http://www.zemanta.com/fruitblog/wikiprep-processing-times/

First, I suggest doing basic tests with "Simple English Wikipedia" dump. Then you could try the dump from Gabrilovich et al. for research purposes. If you're comfortable using Wikiprep-ESA at this point, have TIME and a good computer with many CPUs, then you should consider trying latest Wikipedia English dumps.

**Comment by DavidNemeskey** [comment]
faraday: I have the same question. I downloaded Gabrilovich's 2005 dump, and it contains no disambig file; at least not one with the word "disambig" in its name. The file 20051105_pages_articles.anchor_text.sorted has the same format that you described, but I am not sure if it is the file I am looking for. Could you kindly tell me if that is the disambig file the script is looking for?

**Comment by robinsonkwame** [comment]
My apologies on resurrecting a dead issue but I ran into this today.

Gabrilovich's version of Wikiprep does not output a .disambig flle. The Zumenta fork of Wikiprep does.

scanData.py: 136 assumes that all Wikiprep files conform to the Zumenta fork by only checking  FORMAT != F_ZMODERN. This check includes Gabrilovich's format.

scanData.py: 136 should check FORMAT == F_ZLEGACY, since F_GABRI does not support .disambig. In this case disambigList is empty and scanData.py runs as expected. Changing line 136 to FORMAT == F_ZLEGACY is one solution.

Alternatively, you can create an empty .disambig file, e.g. 20051105_pages_articles.hgw.disambig.
